#!/bin/bash

update() {
    local name="$1"
    local url="$2"
    local location="${3:-$HOME/.bin/${name}}"
    echo -n "Updating ${name}..."
    curl "$url" --silent --location -o "${location}" && chmod 0755 "${location}"
    echo " done."
}

update terminal-colors http://zhar.net/projects/shell/terminal-colors
update sshrc https://raw.githubusercontent.com/Russell91/sshrc/master/sshrc
update ghi https://raw.githubusercontent.com/stephencelis/ghi/master/ghi
update icdiff https://raw.githubusercontent.com/jeffkaufman/icdiff/master/icdiff
update ts https://git.kitenet.net/index.cgi/moreutils.git/plain/ts
update xterm-color-chooser https://raw.githubusercontent.com/grawity/code/master/term/xterm-color-chooser
update spark https://raw.githubusercontent.com/holman/spark/master/spark
update diff-so-fancy https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy

# echo -n "Updating hub completion..."
# curl https://raw.github.com/defunkt/hub/master/etc/hub.zsh_completion --silent --location -o ~/.etc/zsh/zsh/zshrc.d/21_hub_completion
# echo " done."
