#!/bin/bash

update() {
    local name="$1"
    local url="$2"
    echo -n "Updating ${name}..."
    curl $url --silent --location -o ~/.bin/$name && chmod 0755 ~/.bin/$name
    echo " done."
}

update ack http://betterthangrep.com/ack-standalone
update hub http://hub.github.com/standalone
update terminal-colors http://zhar.net/projects/shell/terminal-colors

# echo -n "Updating hub completion..."
# curl https://raw.github.com/defunkt/hub/master/etc/hub.zsh_completion --silent --location -o ~/.etc/zsh/zsh/zshrc.d/21_hub_completion
# echo " done."
