#!/usr/bin/env bash

set -eEu -o pipefail
shopt -s inherit_errexit
IFS=$'\n\t'
PS4='+\t '

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR

[[ "${TRACE:-0}" == "1" ]] && set -x


if [[ $OSTYPE == darwin* ]] || [[ -z "$OSTYPE" && $(uname -o) == Darwin ]]; then
    copy()  { perl -pe "chomp if eof" | pbcopy; }
    paste() { pbpaste | perl -pe "chomp if eof"; }
elif [[ "${XDG_SESSION_TYPE:-}" == wayland ]]; then
    copy()  { wl-copy --trim-newline; }
    paste() { wl-paste --no-newline; }
elif [[ -n "${DISPLAY:-}" ]] && command -v xclip > /dev/null; then
    copy()  { xclip -i -selection clipboard -rmlastnl; }
    paste() { xclip -o -selection clipboard -rmlastnl; }
else
    copy()  {
        local content
        content="$(base64 | perl -pe "chomp if eof")"
        printf "\033]52;c;%s\007" "$content"
    }
    paste() { echo "Pasting not supported with OSC 52" >&2; exit 1; }
fi

if [[ -p /dev/stdin ]]; then
    copy
else
    paste
fi
