#!/bin/bash

set -eEu -o pipefail
IFS=$'\n\t'
PS4='+\t '

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR

if command -v pbpaste > /dev/null; then
    pbpaste
elif [[ -n "${DISPLAY:-}" ]] && command -v xclip > /dev/null; then
    xclip -o -selection clipboard
elif [[ -n "${TMUX:-}" ]]; then
    tmux paste-buffer
else
    echo "No viable clipboard found" >&2
    exit 1
fi
