#!/bin/bash

set -eEu -o pipefail
IFS=$'\n\t'
PS4='+\t '

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR

if command -v pbcopy > /dev/null; then
    pbcopy
elif [[ -n "${DISPLAY:-}" ]] && command -v xclip > /dev/null; then
    xclip -i -selection clipboard
elif [[ -n "${TMUX:-}" ]]; then
    tmux load-buffer -
else
    echo "No viable clipboard found" >&2
    exit 1
fi
