#!/bin/bash
#
# Promotes a local topic branch to a remote tracking branch of the same name,
# by pushing and then setting up the git config

set -e

ORIGIN=${1:-origin}

curr_branch="$(git symbolic-ref --short -q HEAD)"
git push --set-upstream $ORIGIN "${curr_branch}"
