#!/usr/bin/env bash
# List remote branches that have been fully merged, excluding branches that
# just don't have any commits on them yet (which would normally count as
# merged by "git branch --merged").

BRANCHES="$(git branch -r --merged=main | grep -E -v 'origin/(HEAD|main)')"

is_merged() {
    local branch="$1"
    local child="$(git rev-list --ancestry-path --reverse "${branch}"..main | head -1)"
    # local parent="$(git rev-list --parents "$child" -1 | awk '{ print $3 }')"
    local parent
    parent="$(git rev-parse "$child"^2 2>/dev/null)" || return 1
    # [[ -z "$parent" ]] && return 1
    local branch_hash="$(git --no-pager log --pretty="%H" "${branch}" -1)"
    [[ "${branch_hash}" == "${parent}" ]]
}

for branch in $BRANCHES; do
    if is_merged "$branch"; then
        git --no-pager log --pretty=tformat:'%C(auto,yellow)%h%Creset %C(auto,blue)%ai%Creset %C(auto)%d%Creset %s' -1 "${branch}"
    fi
done
