#!/bin/bash
# Reference: https://github.com/neovim/neovim/issues/6435

set -x
set -eEu -o pipefail
IFS=$'\n\t'

UPSTREAM_BRANCH="${1:-master}"
BRANCH="${2:-$(git symbolic-ref --short -q HEAD || echo HEAD)}"

[[ $# -gt 0 ]] && shift
[[ $# -gt 0 ]] && shift

if git merge-base --is-ancestor "$UPSTREAM_BRANCH" "$BRANCH"; then
    BASE_REV=$(git rev-parse "$UPSTREAM_BRANCH")
else
    BASE_REV=$(git merge-base "$UPSTREAM_BRANCH" "$BRANCH")
fi

exec git rebase --interactive "$BASE_REV" "$BRANCH" "$@"
