#!/usr/bin/env python3
# Author: Jan Larres <jan@majutsushi.net>
# License: MIT/X11

import argparse
import signal
from subprocess import run, check_output
import sys
import traceback

import logging
logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.INFO)
log = logging.getLogger(__name__)

try:
    import better_exceptions
except ImportError:
    pass

def sigint_handler(_signal, frame):
    print("Caught interrupt in %s; exiting" % frame.f_code.co_name)
    print(''.join(traceback.format_stack(frame)))
    sys.exit(1)

def parse_args():
    parser = argparse.ArgumentParser(description='Log graph of branch diverge')
    parser.add_argument('rev', nargs='+', help='Revisions to log')
    parser.add_argument('-v', '--verbose', action='store_true', default=False,
                        help='increase output verbosity')
    parser.add_argument('-p', '--print-args',
                        action='store_true', default=False,
                        help="print revision args instead of running git log")
    return parser.parse_args()

def main(args):
    if args.verbose:
        log.setLevel(logging.DEBUG)

    revs = args.rev
    if len(revs) == 1:
        revs += ['HEAD']

    cmd = ['git', 'merge-base', '--octopus', '--all'] + revs
    log.debug(cmd)
    merge_bases = check_output(cmd).decode('utf-8').splitlines()

    exclusions = [base + '^' for base in merge_bases]
    log.debug(exclusions)

    rev_args = revs + ['--not'] + exclusions

    if args.print_args:
        print(" ".join(rev_args))
        sys.exit(0)

    log_cmd = ['git', 'log', '--oneline', '--decorate', '--graph'] + rev_args
    log.debug(log_cmd)
    run(log_cmd)

if __name__ == '__main__':
    signal.signal(signal.SIGINT, sigint_handler)
    sys.exit(main(parse_args()))
