#!/bin/bash

set -eEu -o pipefail
IFS=$'\n\t'

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR


if [[ -z "${1:-}" ]]; then
    echo "usage: $(basename "$0") <path>" >&2
    exit 1
fi

echo -n "WARNING: Dangerous operation! Really purge path '$1' from history? [y/N] "
read -r ans
if  [[ "$ans" == "y" ]]; then
    git filter-branch \
        --prune-empty \
        --index-filter "git rm -r --cached --ignore-unmatch '$1'" \
        --tag-name-filter cat \
        -- \
        --all
else
    echo "Aborting."
fi
