#!/bin/bash

export GTK_DATA_PREFIX=""
export GTK2_RC_FILES=$HOME/.etc/gtk/gtkfix.gtkrc

# GTK3:
# https://developer.gnome.org/gtk3/stable/gtk-running.html
# GTK_THEME=Adwaita:dark gedit
# GTK_THEME=Adwaita:light gedit

if [ -L "$0" ]; then
    cmd="$(basename "$0")"
    set -- "$cmd" "$@"
fi

# Minified path
PATH=/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/games
# Special case one thing: iceweasel
if [[ "$0" =~ iceweasel ]]; then
    eatmydata  "$@"
elif [[ "$0" =~ firefox ]]; then
    shift
    $HOME/apps/firefox/firefox "$@"
else
    "$@"
fi
