#!/bin/bash

if [[ $(pgrep -c xscreensaver) -ge 1 ]]; then
    delay_screensaver() { xscreensaver-command -deactivate >&- 2>&-; }
    # delay_screensaver() { xdotool key shift; }
else
    delay_screensaver() { xset -dpms && xset +dpms; }
fi

get_class() {
    local value=$(xprop -id $active_win_id -notype 8s '=$0+' WM_CLASS | cut -d= -f 2)
    IFS=', ' read -a data <<< $value
    echo ${data[@]//\"}
}

check_fs_apps() {
    local classes=(
        "plugin-container"
        "Navigator"
        "Chromium"
        "vlc"
        "Wine"
    )
    for class in ${classes[@]}; do
        [[ ${active_win_class[0]} == $class ]] && return 0
    done

    local instances=(
        "mpv"
    )
    for instance in ${instances[@]}; do
        [[ ${active_win_class[1]} == $instance ]] && return 0
    done

    return 1
}

check_non_fs_apps() {
    local classes=(
        "phoenix"
        "totem"
    )
    for class in ${classes[@]}; do
        [[ ${active_win_class[0]} == $class ]] && return 0
    done

    return 1
}

delay=$1

if [[ -z "$1" ]];then
    delay=3m
fi

while true; do
    active_win_id=$(xprop -root _NET_ACTIVE_WINDOW)
    if [[ -z "$active_win_id" ]]; then
        sleep $delay
        continue
    fi
    active_win_id=${active_win_id:40:9}
    active_win_class=($(get_class))

    if [[ $active_win_id == 0x0 ]]; then
        continue
    fi

    if xprop -id $active_win_id | grep -qE "(_NET_WM_STATE_FULLSCREEN|plugin-container)"; then
        if check_fs_apps; then
            delay_screensaver
        fi
    fi

    if check_non_fs_apps; then
        delay_screensaver
    fi

    sleep $delay
done
