#!/bin/bash

set -eEu -o pipefail
IFS=$'\n\t'

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR


if (( "${#@}" < 1 )); then
    echo "usage: $0 <command>"
    exit 1
fi

TAG="$(basename "$1")"

exec systemd-cat \
    --identifier="$TAG" \
    --priority=info \
    --stderr-priority=warning \
    "$@"
