#!/usr/bin/env bash

set -eEu -o pipefail
IFS=$'\n\t'
PS4='+\t '

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR

[[ "${TRACE:-0}" == "1" ]] && set -x


# Try gio first since xdg-open defaults to mailcap
# in non-recognized desktop environments
if [[ $OSTYPE == darwin* ]]; then
    exec /usr/bin/open "$@"
elif command -v gio >/dev/null; then
    exec gio open "$@"
elif command -v /usr/bin/xdg-open >/dev/null; then
    exec /usr/bin/xdg-open "$@"
else
    exec /usr/bin/open "$@"
fi
