#!/usr/bin/env bash

set -eEu -o pipefail
IFS=$'\n\t'
PS4='+\t '

error_handler() { echo "Error: Line ${1} exited with status ${2}"; }
trap 'error_handler ${LINENO} $?' ERR

[[ "${TRACE:-0}" == "1" ]] && set -x


FILE_PATH="$1"

has_cmd() {
    type -P "$1" > /dev/null
}

if has_cmd gio; then
    echo "---- shared-mime-info type ----"
    gio info --attributes=standard::content-type "$FILE_PATH" | awk '/standard::content-type/ { print $2 }'
    echo
fi
if has_cmd mimetype; then
    # Print type again because of https://github.com/mbeijen/File-MimeInfo/issues/11
    echo "---- shared-mime-info (Perl) type ----"
    mimetype --dereference --brief --describe "$FILE_PATH"
    mimetype --dereference --brief "$FILE_PATH"
    echo
fi
if [[ "$OSTYPE" == darwin* ]]; then
    echo "---- macOS type ----"
    UTI=$(mdls -name kMDItemContentType "$FILE_PATH" | sed -r -e 's/.*"([^"]+)"/\1/')
    echo "$UTI"
    echo "$UTI" | uti-to-mime
    echo
fi
echo "---- magic(5) type ----"
file --keep-going --dereference --brief "$FILE_PATH" | sed -r -e 's/\\012/\n/g' | head -n -1
echo "----"
file --keep-going --dereference --brief --mime "$FILE_PATH" | sed -r -e 's/\\012/\n/g' | head -n -1

if has_cmd hexyl; then
    echo
    echo "---- First 256 bytes ----"
    hexyl --length 256 --color always "$FILE_PATH"
elif has_cmd hexdump; then
    echo
    echo "---- First 256 bytes ----"
    hexdump -n 256 -C "$FILE_PATH"
fi
